### ISSUE TITLE
Check if track is already in playlist before adding

### ISSUE THREAD

**Issue by h3xar0n** [JorgvanderSchaaf/CcJammming#1]
You have the right approach for adding tracks. Before pushing it to the playlist, we should be careful to check if the track is already there.

https://github.com/JorgvanderSchaaf/CcJammming/blob/b63c781891dcc01e6b026a8fa4f4172bda087d08/src/components/App/App.js#L38-L46

Notice here that there is a conditional that will `return` if the track is already on the playlist, preventing the code beneath it from running:

```javascript
  addTrack(track) {
    let tracks = this.state.playlistTracks;
    if (tracks.find(savedTrack => savedTrack.id === track.id)) {
      return;
    }

    tracks.push(track);
    this.setState({playlistTracks: tracks});
  }
```

**Comment by JorgvanderSchaaf** [comment]
Thanks! I had this not working earlier, but with this I should get this part working. Processed it and will be testing it.

**Comment by JorgvanderSchaaf** [comment]
Tested and works!

**Comment by h3xar0n** [comment]
Awesome, nice work! Can you push the latest version?

**Comment by JorgvanderSchaaf** [comment]
Thanks. I'm first processing some of the other issues. I also have a playlist saving issue I want to solve too. But I will soon push the updated version.
