### ISSUE TITLE
Where is `term` defined?

### ISSUE THREAD

**Issue by h3xar0n** [JorgvanderSchaaf/CcJammming#2]
There is a method that changes the value for the `term` property, but that seems to be missing in the constructor.

https://github.com/JorgvanderSchaaf/CcJammming/blob/b63c781891dcc01e6b026a8fa4f4172bda087d08/src/components/SearchBar/SearchBar.js#L16

If this is throwing errors for you, after `super(props)`, try adding

```javascript
this.state = {
  term: ''
};
```

**Comment by JorgvanderSchaaf** [comment]
Now I understand why I had this issue with the searchbar not taking my initial entry. It only took it in a second try. So yes it did throw me an error. Thanks.

**Comment by JorgvanderSchaaf** [comment]
processed and tested. It's working.
