### ISSUE TITLE
Indentation in JSX

### ISSUE THREAD

**Issue by h3xar0n** [JorgvanderSchaaf/CcJammming#3]
Your indentation and formatting are great. There was one small place that was inconsistent here:

https://github.com/JorgvanderSchaaf/CcJammming/blob/b63c781891dcc01e6b026a8fa4f4172bda087d08/src/components/Track/Track.js#L29-L32

JSX can be especially tricky to read sometimes, so using a tool in your text editor to "tidy" the code will make life easier for you.

**Comment by JorgvanderSchaaf** [comment]
I have Auto Indent active in my Atom text editor. That helps. I don't know of any other tools in Atom to tidy up. I will have look into that.

**Comment by h3xar0n** [comment]
Got it. I use Visual Studio Code's formatting for JSX. For Atom, this tool looks like it will do the trick:
https://orktes.github.io/atom-react/#jsx-reformatting

To install:
`apm install react`
