### ISSUE TITLE
Hide API client ID from public repo

### ISSUE THREAD

**Issue by h3xar0n** [JorgvanderSchaaf/CcJammming#4]
On the top line in Spotify.js, the client ID is visible. While this may not be a problem for Stripe per se, in general, many APIs do not want this information shared, since a bot could easily grab it and abuse their API pretending to be you.

These are a set of steps to hide sensitive information in your repos:

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by JorgvanderSchaaf** [comment]
Thanks, it was mentioned in the project steps, I had set a mental note, and I still forgot to do this. How do developers make sure they don't forgot this or any other such security step?

**Comment by JorgvanderSchaaf** [comment]
I guess I will read it in the article.
