### ISSUE TITLE
Feature Request: Populating search results on keypress

### ISSUE THREAD

**Issue by zannain** [JorgvanderSchaaf/CcJammming#9]
Be careful with the onKeypress because as you mentioned this can impact performance. One thing you may want to consider that you often see when typing an address in a form is when results become more accurate the more you type underneath the input element. You could reuse a lot of the code you already have for Search Results but downsize it to fit in a short drop-down. You could even add the image you mentioned, albeit it would be slightly smaller. Also consider caching images to improve performance, though with as fast as React is this won't make a huge difference in performance. A good way to check the performance of your application is by using the developer tools and clicking Record in the Network tab and then making a search and comparing the results.

**Comment by JorgvanderSchaaf** [comment]
Nice, thanks. I have put in the 'Search on pressing enter' feature and tested the performance. There was no performance loss. The fetch took still between 18 and 22 milliseconds.

**Comment by JorgvanderSchaaf** [comment]
I will also add the images later on. For now I have to deal with the tracks not being saved to the saved playlists and I couldn't figure it out yet.
